name: Waka Readme Stats

on:
  workflow_dispatch: # Allows you to run this workflow manually
  schedule:
    # Runs every 4 hours
    - cron: "0 */6 * * *"

jobs:
  update-readme:
    name: Update Readme with WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          # Required
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub automatically provides this

          # Options
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_EDITORS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_COMMIT: "False"
          SHOW_LANGUAGE: "True"
          SHOW_LINES_OF_CODE: "True"
